apiVersion: apps/v1
kind: Deployment
metadata:
  name: drun
spec:
  selector:
    matchLabels:
      app: drun
  replicas: 2
  template:
    metadata:
      labels:
        app: drun
    spec:
      containers:
      - name: drun
        image: nanajanashia/argocd:1.0
        ports:
        - containerPort: 8080
