---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: 823787da3ea005ac24459bace7cb3cd5ad0ba86a
  labels:
    version: v1
    app.kubernetes.io/version: java-maven-8.0
    app.kubernetes.io/name: demo-app
  name: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      version: v1
      app.kubernetes.io/version: java-maven-8.0
      app.kubernetes.io/name: demo-app
  template:
    metadata:
      annotations:
        app.dekorate.io/vcs-url: <<unknown>>
        app.dekorate.io/commit-id: 823787da3ea005ac24459bace7cb3cd5ad0ba86a
      labels:
        version: v1
        app.kubernetes.io/version: java-maven-8.0
        app.kubernetes.io/name: demo-app
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: nbglink/demo-app:java-maven-8.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: demo-app
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: 823787da3ea005ac24459bace7cb3cd5ad0ba86a
  labels:
    app.kubernetes.io/name: demo-app
    version: v1
    app.kubernetes.io/version: java-maven-8.0
  name: demo-app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/name: demo-app
    version: v1
    app.kubernetes.io/version: java-maven-8.0
  type: LoadBalancer