apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drun-drun
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/nbglink/DevOpsUpskill-FinalProject-Infra.git
    targetRevision: HEAD
    path: ./argocd-app-config/newapp
  destination: 
    server: https://kubernetes.default.svc
    namespace: newapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true